version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - docker build -t codebuild-test .
  post_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 661313633896.dkr.ecr.ap-northeast-1.amazonaws.com
      - docker tag codebuild-test:latest 661313633896.dkr.ecr.ap-northeast-1.amazonaws.com/codebuild-docker:latest
      - docker push 661313633896.dkr.ecr.ap-northeast-1.amazonaws.com/codebuild-docker:latest
artifacts:
  type: zip
  files:
    - first.txt
