version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"
    CONTAINER_NAME: codebuild-docker
phases:
  install:
    commands:
      - echo install..................................
  pre_build:
    commands:
      - echo pre_build..................................
  build:
    commands:
      - REPOSITORY_URI=${ECR_URI}
      - IMAGE_TAG=$(date "+%Y.%m.%d.%H.%M")
      - echo REPOSITORY_URI:${REPOSITORY_URI}
      - echo CONTAINER_NAME:${CONTAINER_NAME}
      - echo IMAGE_TAG:${IMAGE_TAG}
      - docker build -t ${CONTAINER_NAME}:${IMAGE_TAG} .
  post_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - docker tag ${CONTAINER_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}/${CONTAINER_NAME}:${IMAGE_TAG}
      - docker push ${REPOSITORY_URI}/${CONTAINER_NAME}:${IMAGE_TAG}
      - echo "[{\"name\":\"${CONTAINER_NAME}\",\"imageUri\":\"${REPOSITORY_URI}/${CONTAINER_NAME}:${IMAGE_TAG}\"}]" > imagedefinitions.json
      - echo "{\"Version\":\"1.0\",\"ImageURI\":\"${REPOSITORY_URI}/${CONTAINER_NAME}:${IMAGE_TAG}\"}"  > imageDetail.json
artifacts:
  files:
    - imagedefinitions.json
    - imageDetail.json
