version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"
phases:
  install:
    commands:
      - echo Hello, now $(date "+%Y-%m-%d %H:%M").
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - REPOSITORY_URI=${ECR_URI}
      - CONTAINER_NAME=codebuild-docker
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker build -t ${CONTAINER_NAME}:$IMAGE_TAG .
  post_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - docker tag ${CONTAINER_NAME}:$IMAGE_TAG $REPOSITORY_URI/${CONTAINER_NAME}:$IMAGE_TAG
      - docker push $REPOSITORY_URI/${CONTAINER_NAME}:$IMAGE_TAG
      - echo "[{\"name\":\"${CONTAINER_NAME}\",\"imageUri\":\"${REPOSITORY_URI}/${CONTAINER_NAME}:${IMAGE_TAG}\"}]" > imagedefinitions.json
      - echo "[{\"name\":\"${CONTAINER_NAME}\",\"imageUri\":\"${REPOSITORY_URI}/${CONTAINER_NAME}:${IMAGE_TAG}\"}]"
artifacts:
  files: imagedefinitions.json
